# Site settings
title: Team MASA
email: na
description: > # this means to ignore newlines until "baseurl:"
  Team MASA
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
